### PR TITLE
Version one of my component library

### PR DESCRIPTION
**Pull request by Akshaay9**
Hello, 
Here is the link of Live Website : https://ui-wordl-v1.netlify.app/
Please feel free to go throught it
 Any feedback would be highly appreciated 
Thank You.

### CODE REVIEW

**Comment by uditkumar01** [comment]
Bug:
Screenshot_2021-03-26 Component Library
Suggestion footer should not be in white color(try #e6e6e6) or you can give color options like primary, secondary, etc.

**Comment by ishanjirety** [comment]
image
-> Avoid writing inline css
image
-> Fix spacing

**Comment by Akshaay9** [comment]
> image
> -> Avoid writing inline css
> image
> -> Fix spacing

Yeah, Sure.
actully i wanted to keep only component related code on my CSS files. so i have used inline in some places where styling was not related to my  components.
Thank You For your feedback

**Comment by Akshaay9** [comment]
> Bug:
> Screenshot_2021-03-26 Component Library
> Suggestion footer should not be in white color(try #e6e6e6) or you can give color options like primary, secondary, etc.

Done With the changes
Thank you  For Your FeedBack

**Comment by sdhamani** [comment]
Hi Akshay,
The code really looks good.

One thing I liked the most is that you have used variables for all the colors in your css file.
Only thing is to avoid inline css.
But I guess the code is good to go,
Great work.

**Comment by Akshaay9** [comment]
> Hi Akshay,
> The code really looks good.
> 
> One thing I liked the most is that you have used variables for all the colors in your css file.
> Only thing is to avoid inline css.
> But I guess the code is good to go,
> Great work.

Thank you for your feedback.

**Comment by ishanjirety** [comment]
Hi Akshay,
The component library looks good now and can be merged.

**Pull request merged**
